name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Electronic-Prescription-Service-Build"
      trigger:
        branches:
          exclude:
            - master
            - refs/heads/master
            - refs/tags/v*

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml
  - group: pact
  - group: eps-smoke-tests

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: false
    enable_status_monitoring: false
    manual_approval_env: manual-approval-ptl
    jinja_templates:
      REQUIRE_ASID: false
    apigee_deployments:
      #      - environment: internal-dev-sandbox
      #        proxy_path: sandbox
      #        secret_file_ids:
      #          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
      #          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      #        post_deploy:
      #          - template: ./templates/run_tests.yml
      - environment: internal-dev
        proxy_path: live
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
        post_deploy:
          - template: ./templates/run_tests.yml
