name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Electronic-Prescription-Service-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml
  - group: pact
  - group: eps-ref-smoke-tests
  - group: eps-smoke-tests

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    manual_approval_env: manual-approval-ptl
    jinja_templates:
      REQUIRE_ASID: false
    apigee_deployments:
      - environment: manual-approval
        stage_name: qa_manual_approval
      - environment: manual-approval
        stage_name: ref_manual_approval
      - environment: manual-approval
        stage_name: ptl_manual_approval
      - environment: manual-approval
        stage_name: prod_manual_approval
      - environment: internal-dev
        proxy_path: live
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
        post_deploy:
          - template: ./templates/post_dev_deploy.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
        post_deploy:
          - template: ./templates/run_tests.yml
      - environment: internal-qa
        proxy_path: live
        depends_on:
          - internal_dev
          - qa_manual_approval
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
        post_deploy:
          - template: ./templates/run_tests.yml
      - environment: ref
        proxy_path: live
        depends_on:
          - internal_dev
          - ref_manual_approval
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - internal_qa
          - ptl_manual_approval
        post_deploy:
          - template: ./templates/run_tests.yml
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: int
        proxy_path: live
        depends_on:
          - internal_qa
          - ptl_manual_approval
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
        pre_deploy:
          - template: ./templates/pre_int_deploy.yml
        post_deploy:
          - template: ./templates/post_int_deploy.yml
      - environment: prod
        proxy_path: live
        depends_on:
          - sandbox
          - int
          - prod_manual_approval
        jinja_templates:
          REQUIRE_ASID: true
        post_deploy:
          - template: ./templates/post_prod_deploy.yml
