name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Electronic-Prescription-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - group: pact

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    service_base_path_pr: ${{ variables.service_base_path_pr }}
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: false
    jinja_templates:
        REQUIRE_ASID: false
    apigee_deployments:
      - environment: internal-dev-sandbox
        proxy_path: sandbox
      - environment: internal-dev
        proxy_path: live
        make_spec_visible: true
