name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/mm-apm-1351-aws-build-agents
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    test_steps:
      - bash: "make test"
        displayName: Run Quality Checks
        workingDirectory: "${{ variables.service_name }}"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'coordinator/newman/*.xml'
          failTaskOnFailedTests: true
          workingDirectory: ${{ variables.service_name }}
    post_ecs_push:
      - bash: "scripts/populate_ssm_parameters.sh"
        displayName: Copy secrets from secrets manager to SSM
        workingDirectory: ${{ variables.service_name }}
