#########################################################################
# Dependabot configuration file
#########################################################################

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DEPENDABOT_TOKEN}}

updates:
  ###################################
  # Poetry  #########################
  ###################################
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" #UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
    versioning-strategy: increase
  # Coordinator Container
  - package-ecosystem: "docker"
    directory: "/packages/coordinator"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00" #UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
  # EPSAT Container
  - package-ecosystem: "docker"
    directory: "/packages/tool/site"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00" #UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00" #UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
  ###################################
  # NPM workspace  ##################
  ###################################
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00" #UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
    versioning-strategy: increase
    registries:
      - npm-github
