vulnerabilities:
  - id: CVE-2026-24842
    statement: downstream dependency for tar - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2023-24057
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-28465
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-45294
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-52007
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-45294
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-52007
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-45294
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-52007
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-24057
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-28465
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-45294
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-52007
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-24057
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-28465
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-45294
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-52007
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-24057
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2023-28465
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-51132
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2021-35515
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2021-35516
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2021-35517
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2021-36090
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2022-42889
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2024-55887
    statement: hapi-fhir vulnerability accepted as risk
    expired_at: 2027-01-01
  - id: CVE-2026-25128
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb
    expired_at: 2026-03-01
  - id: CVE-2026-26278
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb
    expired_at: 2026-06-01
  - id: CVE-2026-26960
    statement: tar vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-2699
    statement: tar vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-26996
    statement: minimatch vulnerability accepted as risk
    expired_at: 2026-06-01
