[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
addopts = -v --tb=short --cov=app --cov-report=xml:coverage/coverage.xml --cov-report=term-missing --cov-config=pytest.ini

[coverage:run]
omit = */__init__.py
