# syntax=docker/dockerfile:1

# --- Dependencies ---
FROM node:12.18.1-alpine as base
WORKDIR /app

# --- Build Client ---
FROM node:12.18.1-alpine as build-client
WORKDIR /build
COPY client/package*.json ./
RUN npm ci
COPY client/ ./client
RUN rm client/tsconfig.json
RUN rm client/webpack.config.js
COPY client/tsconfig.json ./
COPY client/webpack.config.js ./
RUN npm run build:prod

# --- Build Hapi Server ---
FROM node:12.18.1-alpine as build-hapi-server
WORKDIR /build
COPY server_hapi/package*.json ./
RUN npm ci
COPY server_hapi/tsconfig.json ./
COPY server_hapi/src src
RUN npm run build:prod

# --- Runtime ---
FROM base AS runtime
ENV NO_UPDATE_NOTIFIER true
COPY --from=build-client /build/static ./static
COPY --from=build-client /build/templates ./templates
COPY --from=build-hapi-server /build/node_modules node_modules
COPY --from=build-hapi-server /build/dist/ ./
COPY --from=build-hapi-server /build/package*.json ./
RUN chmod -R a+x /app
USER nobody
CMD ["npm", "run", "start"]