# syntax=docker/dockerfile:1

# --- Dependencies ---
FROM node:12.18.1-alpine as base
WORKDIR /app

# --- Build Hapi Server ---
FROM node:12.18.1-alpine as build-hapi-server
WORKDIR /build
COPY server_hapi/package*.json ./
RUN npm ci
COPY server_hapi/tsconfig.json ./
COPY server_hapi/src src
RUN npm run build:prod

# --- Runtime ---
FROM base AS runtime
ENV NO_UPDATE_NOTIFIER true
COPY --from=build-hapi-server /build/node_modules node_modules
COPY --from=build-hapi-server /build/dist/ ./
COPY --from=build-hapi-server /build/package*.json ./
RUN chmod -R a+x /app
USER nobody
CMD ["npm", "run", "start"]
