name: run EPSAT E2E tests

on:
  workflow_dispatch:
    inputs:
      SERVICE_BASE_PATH:
        description: "The service base path to test against"
        required: true
        type: string
      APIGEE_ENVIRONMENT:
        description: "The Apigee environment to test against"
        required: true
        type: string
      id:
        description: "Unique run identifier (Do not change this)"
        required: false
        default: "Manually Triggered Run"
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    with:
      verify_published_from_main_image: false

  run_epsat_tests:
    runs-on: ubuntu-22.04
    needs: [get_config_values]
    container:
      image: ${{ needs.get_config_values.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Workflow identifier ${{ inputs.id }}
        run: echo "Workflow running"
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: make install
        run: |
          make install

      - name: run epsat tests
        run: |
          if [ "${APIGEE_ENVIRONMENT}" == "internal-dev-sandbox" ] || [ "${APIGEE_ENVIRONMENT}" == "sandbox" ]
          then
              npm run test-sandbox --workspace packages/tool/e2e-tests
          else
              npm run test-live --workspace packages/tool/e2e-tests
          fi
        env:
          SERVICE_BASE_PATH: ${{ inputs.SERVICE_BASE_PATH }}
          APIGEE_ENVIRONMENT: ${{ inputs.APIGEE_ENVIRONMENT }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        name: upload test_results
        with:
          name: test_results
          path: |
            packages/tool/e2e-tests/test_results
