name: Update devcontainer version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

permissions: {}

jobs:
  update-devcontainer-version:
    runs-on: ubuntu-22.04
    environment: create_pull_request
    permissions:
      contents: read
      packages: read

    steps:
      - name: Update devcontainer version
        uses: NHSDigital/eps-update-devcontainer@83f4b56f1942635f2c05b7fe569142459b8c3882
        with:
          calling_repo_base_branch: master
          CREATE_PULL_REQUEST_APP_ID: ${{ secrets.CREATE_PULL_REQUEST_APP_ID }}
          CREATE_PULL_REQUEST_PEM: ${{ secrets.CREATE_PULL_REQUEST_PEM }}
